// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A document optimization AI agent.
 *
 * - getDocumentOptimizationSuggestions - A function that handles the document optimization process.
 * - GetDocumentOptimizationSuggestionsInput - The input type for the getDocumentOptimizationSuggestions function.
 * - GetDocumentOptimizationSuggestionsOutput - The return type for the getDocumentOptimizationSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetDocumentOptimizationSuggestionsInputSchema = z.object({
  documentText: z
    .string()
    .describe('The text content of the financial document to optimize.'),
  borrowerProfile: z
    .string()
    .describe('The profile of the borrower, including financial history and goals.'),
});
export type GetDocumentOptimizationSuggestionsInput = z.infer<
  typeof GetDocumentOptimizationSuggestionsInputSchema
>;

const GetDocumentOptimizationSuggestionsOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('A list of suggestions to optimize the financial document.'),
  explanation: z.string().describe('An explanation of why these suggestions are recommended.'),
});
export type GetDocumentOptimizationSuggestionsOutput = z.infer<
  typeof GetDocumentOptimizationSuggestionsOutputSchema
>;

export async function getDocumentOptimizationSuggestions(
  input: GetDocumentOptimizationSuggestionsInput
): Promise<GetDocumentOptimizationSuggestionsOutput> {
  return getDocumentOptimizationSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getDocumentOptimizationSuggestionsPrompt',
  input: {schema: GetDocumentOptimizationSuggestionsInputSchema},
  output: {schema: GetDocumentOptimizationSuggestionsOutputSchema},
  prompt: `You are an AI assistant specializing in providing suggestions for optimizing financial documents to improve the chances of loan approval.

  Based on the content of the financial document and the borrower's profile, suggest specific improvements and explain why these improvements are recommended.

  Financial Document Content: {{{documentText}}}
  Borrower Profile: {{{borrowerProfile}}}

  Suggestions should be clear, actionable, and directly related to improving the document's effectiveness in securing loan approval.

  Format your output as a JSON object with 'suggestions' (an array of strings) and 'explanation' (a string).
  `,
});

const getDocumentOptimizationSuggestionsFlow = ai.defineFlow(
  {
    name: 'getDocumentOptimizationSuggestionsFlow',
    inputSchema: GetDocumentOptimizationSuggestionsInputSchema,
    outputSchema: GetDocumentOptimizationSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
