

type DocumentList = {
    borrower: string[];
    company: string[];
    subjectProperty: string[];
}

export const loanProgramDocumentLists: Record<string, DocumentList> = {
    "Residential NOO - Ground Up Construction": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Executed Purchase Contract",
            "Evidence of Earnest Money Deposit",
            "General Contractor License",
            "General Contractor Insurance",
            "General Contractor Bond",
            "General Contractor's Contract to Build",
            "Construction Budget",
            "Projected Draw Schedule",
            "Builder's Risk Insurance Quote",
            "Commercial Liability Insurance Quote",
            "Approved or Pre-approved Plans (if available)",
            "Approved Permits (if available)",
            "Property HUD-1/Settlement Statement (if already purchased)",
            "30-Day Payoff Statement with Per Diem (if property has a mortgage)",
            "Preliminary Title Commitment",
            "Escrow Instructions",
            "Closing Protection Letter",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Residential NOO - Fix and Flip": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
            "Proof of Funds for down payment and reserves"
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Executed Purchase Contract",
            "Evidence of Earnest Money Deposit",
            "Preliminary Title Commitment",
            "Escrow Instructions",
            "Closing Protection Letter",
            "Rehab Budget",
            "Property HUD-1/Settlement Statement (if already purchased)",
            "30-Day Payoff Statement with Per Diem (if property has a mortgage)",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
            "General Contractor License",
            "General Contractor Insurance",
            "General Contractor Bond",
            "General Contractor's Contract to Build",
            "Construction Budget",
            "Projected Draw Schedule"
        ]
    },
    "Residential NOO - DSCR": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Purchase and Sale Agreement (or HUD-1 if refinance)",
            "Lease Agreements for subject property (if applicable)",
            "Projected Lease Comparables (if vacant)",
            "Commercial Liability Insurance Quote",
            "Preliminary Title Commitment",
            "Escrow Instructions",
            "Closing Protection Letter",
            "30-Day Payoff Statement with Per Diem (if a refinance)",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Residential NOO - Bridge": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
            "Proof of Funds for down payment and reserves",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Executed Purchase Contract",
            "Evidence of Earnest Money Deposit",
            "Preliminary Title Commitment",
            "Escrow Instructions",
            "Closing Protection Letter",
            "Property HUD-1/Settlement Statement (if already purchased)",
            "30-Day Payoff Statement with Per diem (if property has a mortgage)",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Commercial - Ground Up Construction": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Executive Summary",
            "Pro-forma Projections (5 years, month-by-month)",
            "Sources and Uses Statement",
            "Construction Plans",
            "Construction Budget",
            "Environmental Report",
            "Purchase and Sale Agreement (or HUD-1 if refinance)",
            "Evidence of Earnest Money Deposit",
            "30-Day Payoff Statement with Per Diem (if refinance)",
            "Preliminary Title Commitment",
            "Escrow Instructions",
            "Closing Protection Letter",
            "Builder's Risk Insurance Quote",
            "Commercial Liability Insurance Quote",
            "Approved or Pre-approved Plans (if available)",
            "Approved Permits (if available)",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Commercial - Rehab Loans": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Current Rent Roll",
            "Rehab Budget and Plans",
            "Purchase Agreement (if applicable)",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
            "General Contractor License",
            "General Contractor Insurance",
            "General Contractor's Contract to Build",
        ]
    },
    "Commercial - Acquisition & Bridge": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Trailing 12-month Operating Statement",
            "Purchase Agreement",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Commercial - Conventional Long Term Debt": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Current Rent Roll",
            "Lease Agreements",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Industrial - Ground Up Construction": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Proof of Equity Injection",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
            "Business Plan with projections",
        ],
        subjectProperty: [
            "Construction Plans, Budget, and Timeline",
            "Environmental Reports",
            "Approved or Pre-approved Plans (if available)",
            "Approved Permits (if available)",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Industrial - Rehab & Expansion": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Current Property Operating Statements",
            "Rehab/Expansion Plans and Budget",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Industrial - Acquisition & Bridge": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Trailing 12-month Operating Statement for property",
            "Purchase Agreement",
            "Preliminary Title Report",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Industrial - Long Term Debt": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Purchase HUD-1 (if applicable)",
            "Disposition HUD-1 (if applicable)",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Property Operating Statements (3 years)",
            "Lease Agreements",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "SBA 7(a)": {
        borrower: [
            "SBA Form 1919",
            "Personal Financial Statement (SBA Form 413)",
        ],
        company: [
            "Business Financial Statements (3 years)",
            "Business Tax Returns (3 years)",
            "Business Plan and Projections",
            "Partnership/Officer List",
        ],
        subjectProperty: ["Appraisal", "Collateral Desktop Analysis"]
    },
    "SBA 504": {
        borrower: [
            "Personal Financial Statement for all guarantors",
        ],
        company: [
            "SBA Form 1244",
            "Business Financial Statements (3 years)",
            "Partnership/Officer List",
        ],
        subjectProperty: [
            "Project Cost Details",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Land Acquisition": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
        ],
        subjectProperty: [
            "Purchase Agreement",
            "Feasibility Study",
            "Zoning and Entitlement Documents",
            "Environmental Report",
            "Property Tax Certificate",
            "Appraisal",
            "Collateral Desktop Analysis",
        ]
    },
    "Mezzanine Loans": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
            "Sponsor Financials",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
            "Capital Stack overview",
        ],
        subjectProperty: [
            "Senior Debt Term Sheet",
            "Full Project Pro-forma",
        ]
    },
    "Mobilization Funding": {
        borrower: [
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
            "3 Months Personal Asset Statements",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
            "Company Financials",
        ],
        subjectProperty: [
            "Executed Contract for the project",
            "Detailed Use of Funds",
        ]
    },
    "Equipment Financing": {
        borrower: [
            "Application Form",
            "ID/Driver's License",
            "Personal Financial Statement",
            "Credit Report",
        ],
        company: [
            "Company Asset Statement",
            "EIN Certificate",
            "Formation Documentation",
            "Operating Agreement/Bylaws",
            "Partnership/Officer List",
            "Business License",
            "Certificate of Good Standing",
            "Business Debt Schedule",
            "Business Financials (if over $100k)",
        ],
        subjectProperty: [
            "Equipment Quote or Invoice",
        ]
    },
    "Default": {
        borrower: ["ID/Driver's License", "Personal Financial Statement", "Credit Report"],
        company: ["EIN Certificate", "Formation Documentation", "Operating Agreement/Bylaws", "Partnership/Officer List"],
        subjectProperty: ["Purchase and Sale Agreement", "Appraisal Report"]
    }
}
