// This is an autogenerated file from Firebase Studio.

import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';

const firebaseConfig = {
  projectId: 'lankford-lending',
  appId: '1:940157326397:web:02fbefc8cd0a13c2160654',
  storageBucket: 'lankford-lending.appspot.com',
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: 'lankford-lending.firebaseapp.com',
  messagingSenderId: '940157326397',
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export {app, auth, db, storage};
