// This is an autogenerated file from Firebase Studio.

import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';

const firebaseConfig = {
  "apiKey": "API_KEY",
  "authDomain": "lankford-lending.firebaseapp.com",
  "projectId": "lankford-lending",
  "storageBucket": "lankford-lending.appspot.com",
  "messagingSenderId": "488394495446",
  "appId": "1:488394495446:web:a62b32d207865223c72b53",
  "measurementId": "G-404W344P0H"
};


const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export {app, auth, db, storage};
