// This is an autogenerated file from Firebase Studio.

'use client';

import {ProtectedRoute} from '@/components/protected-route';

export default function BrokerOfficeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute redirectTo="/auth/signin?role=broker">
      <div className="bg-primary/5 min-h-screen">{children}</div>
    </ProtectedRoute>
  );
}
