// This is an autogenerated file from Firebase Studio.

'use client';

import {ProtectedRoute} from '@/components/protected-route';

export default function WorkforceOfficeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute redirectTo="/auth/workforce-signin">{children}</ProtectedRoute>
  );
}
