// This is an autogenerated file from Firebase Studio.

'use client';

import {useRouter} from 'next/navigation';
import {useEffect, useState, ReactNode} from 'react';
import {useAuth} from '@/contexts/auth-context';
import {Skeleton} from '@/components/ui/skeleton';

export const ProtectedRoute = ({
  children,
  redirectTo = '/auth/signin',
}: {
  children: ReactNode;
  redirectTo?: string;
}) => {
  const {user, loading} = useAuth();
  const router = useRouter();
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  useEffect(() => {
    if (isClient && !loading && !user) {
      router.push(redirectTo);
    }
  }, [user, loading, router, isClient, redirectTo]);

  if (loading || !isClient) {
    return (
      <div className="space-y-4 p-4">
        <Skeleton className="h-12 w-1/4" />
        <div className="grid grid-cols-3 gap-4">
          <Skeleton className="h-24" />
          <Skeleton className="h-24" />
          <Skeleton className="h-24" />
        </div>
        <Skeleton className="h-64" />
      </div>
    );
  }

  return user ? children : null;
};
