// This is an autogenerated file from Firebase Studio.

'use client';

import {useRouter} from 'next/navigation';
import {useEffect, useState, ReactNode} from 'react';
import {useAuth} from '@/contexts/auth-context';
import {Skeleton} from '@/components/ui/skeleton';
import { Loader2 } from 'lucide-react';

function ProtectedRouteSkeleton() {
  return (
    <div className="flex h-screen w-full items-center justify-center">
      <Loader2 className="h-8 w-8 animate-spin" />
    </div>
  )
}


export const ProtectedRoute = ({
  children,
  redirectTo = '/auth/signin',
}: {
  children: ReactNode;
  redirectTo?: string;
}) => {
  const {user, loading} = useAuth();
  const router = useRouter();
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  useEffect(() => {
    if (isClient && !loading && !user) {
      router.push(redirectTo);
    }
  }, [user, loading, router, isClient, redirectTo]);

  if (loading || !isClient || !user) {
    return <ProtectedRouteSkeleton />;
  }
  
  return user ? children : null;
};
